name: "CI"

on:
  push:
    branches:
      - master
env:
  commit_message: ${{ github.event.head_commit.message }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
