name: "Teste Nilton CI"

on:
  push:
    branches:
      - master
env:
  commit_message: ${{ github.event.head_commit.message }}


jobs:
  deploy-psti-homol:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set Slack Name in Env
      run: echo "slack_name=Deploy-PSTI-HOMOL" >> $GITHUB_ENV
    - name: Get Message
      run: echo "deploy_app=$(echo $commit_message|grep deploy:|cut -d':' -f2)" >> $GITHUB_ENV

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "${{ env.deploy_app }}/app.yaml"


    - name: 'Deploy to App Engine'
      if: steps.check_files.outputs.files_exists == 'false'
      run: 'echo "O arquivo ${{ env.deploy_app }}/app.yaml nao existe ..."'
      #run: 'gcloud app deploy ${{ env.deploy_app }}/app.yaml --quiet --no-promote --version NILTON'
